stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.7
  before_script:
    - pip install git+https://github.com/cedadev/directory-tree.git
    - pip install -e $CI_PROJECT_DIR
    - pip install requests
    - pip install -e git+https://github.com/rsmith013/cci-tagger.git
  script:
    - python cci-tagger/scripts/check_json.py cci_tagger_json/json/*/*.json

deploy:
  stage: deploy
  variables:
    BUILD_ARG_JSON_GIT_VERSION: $CI_COMMIT_SHA
  trigger: rsmith013/rabbit_indexer_docker
  only:
    - master