stages:
  - test

test:
  stage: test
  image: python:3.7
  before_script:
    - pip install git+https://github.com/cedadev/directory-tree.git
    - pip install -e $CI_PROJECT_DIR
    - pip install git+https://github.com/rsmith013/cci-tagger.git
  script:
    - cci_json_check cci_tagger_json/json/*/*.json
